{% set version = "1.4.0" %}

package:
  name: wrf-python
  version: {{ version }}

source:
  url: https://github.com/NCAR/wrf-python/archive/v{{ version }}.tar.gz
  sha256: 831600abbf4037c33a55c11ca9da5f8ee97b8b0276c205de8ab66cef85ff3589

build:
  number: 0
  detect_binary_files_with_prefix: true
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env:
    - SKBUILD_CONFIGURE_OPTIONS=-DCMAKE_Fortran_COMPILER=gfortran
  skip: true  # [py==313]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - cmake
    - make  # [unix]
    - ninja  # [win]
  host:
    - setuptools
    - pip
    - python
    - python-build
    - numpy
    - scikit-build-core
    # upstream has it as a requirement
    - wrapt
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - setuptools
    - wrapt
    - xarray

test:
  requires:
    - netcdf4
    - xarray
  source_files:
    - test/ci_tests
  imports:
    - wrf
  commands:
    - cd test/ci_tests && python utests.py

about:
  home: https://github.com/NCAR/wrf-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Diagnostic and interpolation routines for WRF-ARW data.

extra:
  recipe-maintainers:
    - akrherz
    - erogluorhan
    - kafitzgerald
