{% set version = "1.3.2" %}

package:
  name: wrf-python
  version: {{ version }}

source:
  fn: wrf-python-{{ version }}.tar.gz
  url: https://github.com/NCAR/wrf-python/archive/{{ version }}.tar.gz
  sha256: 1c228548f88848689168d0a4bc41a531123c87f9c552fe75fb1eadd091d3ad26 

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}
  host:
    - setuptools
    - python
    - numpy  # [unix]
    - numpy 1.18.*  # [win]
    - wrapt
  run:
    - setuptools
    - {{ pin_compatible('numpy') }}
    - python
    - wrapt
    - xarray

test:
  requires:
    - setuptools
    - netcdf4
    - xarray
  source_files:
    - test/ci_tests
  imports:
    - wrf
  commands:
    - cd test/ci_tests && python utests.py

about:
  home: https://github.com/NCAR/wrf-python
  license: "Apache-2.0"
  license_file: LICENSE
  summary: "Diagnostic and interpolation routines for WRF-ARW data."

extra:
  recipe-maintainers:
    - bladwig1
    - marylhaley
    - khallock
