{% set version = "1.3.2.6" %}

package:
  name: wrf-python
  version: {{ version }}

source:
  url: https://github.com/NCAR/wrf-python/archive/{{ version }}.tar.gz
  sha256: e137f95a02cc25629bb686d93e31068fd0f76150b3a9fabd913dd19caf9ddaf7

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}
  host:
    - setuptools
    - python
    - pip
    - numpy  # [not win]
    - numpy 1.14.*  # [win]
  run:
    - {{ pin_compatible('numpy') }}
    - numpy =1.19.5  # [win]
    - python
    - wrapt
    - xarray

test:
  requires:
    - netcdf4
    - xarray
  source_files:
    - test/ci_tests
  imports:
    - wrf
  commands:
    - cd test/ci_tests && python utests.py

about:
  home: https://github.com/NCAR/wrf-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Diagnostic and interpolation routines for WRF-ARW data.

extra:
  recipe-maintainers:
    - michaelavs
    - erogluorhan
