{% set version = "1.3.4.1" %}

package:
  name: wrf-python
  version: {{ version }}

source:
  url: https://github.com/NCAR/wrf-python/archive/v{{ version }}.tar.gz
  sha256: 334aa79ce3c608ca064c55491f249dd7c039ab22e20324a9e16d9ea015ce1fae

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}
  host:
    - setuptools
    - python
    - numpy
    # upstream has it as a requirement
    - wrapt
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - wrapt
    - xarray

test:
  requires:
    - netcdf4
    - xarray
  source_files:
    - test/ci_tests
  imports:
    - wrf
  commands:
    - cd test/ci_tests && python utests.py

about:
  home: https://github.com/NCAR/wrf-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Diagnostic and interpolation routines for WRF-ARW data.

extra:
  recipe-maintainers:
    - akrherz
    - michaelavs
    - erogluorhan
