{% set version = "1.3.2.5" %}

package:
  name: wrf-python
  version: {{ version }}

source:
  fn: wrf-python-{{ version }}.tar.gz
  url: https://github.com/NCAR/wrf-python/archive/{{ version }}.tar.gz
  sha256: 8e54b2bca0fb095d9f94094cbe1463d74a351c5004930f4411fb963634589db4

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}
  host:
    - setuptools
    - python
    - numpy  # [unix]
    - numpy 1.14.*  # [win]
    - wrapt
  run:
    - setuptools
    - {{ pin_compatible('numpy') }}
    - python
    - wrapt
    - xarray

test:
  requires:
    - setuptools
    - netcdf4
    - xarray
  source_files:
    - test/ci_tests
  imports:
    - wrf
  commands:
    - cd test/ci_tests && python utests.py

about:
  home: https://github.com/NCAR/wrf-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Diagnostic and interpolation routines for WRF-ARW data.

extra:
  recipe-maintainers:
    - michaelavs
    - erogluorhan
