{% set version = "1.4.2" %}

package:
  name: wrf-python
  version: {{ version }}

source:
  url: https://github.com/NCAR/wrf-python/archive/v{{ version }}.tar.gz
  sha256: 48f360e3319c782e44653bc1e907842724873561c17dbbf1fe56ff625d3dab35

build:
  number: 1
  detect_binary_files_with_prefix: true
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env:
    - CMAKE_ARGS=-DCMAKE_Fortran_COMPILER:FILEPATH=%BUILD_PREFIX%\Library\mingw-w64\bin\x86_64-w64-mingw32-gfortran.exe  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}  # [unix]
    - {{ stdlib("c") }}  # [unix]
    - {{ compiler('c') }}  # [unix]
    - cmake
    - make  # [unix]
    - ninja  # [win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - m2-make  # [win]
    - m2-which  # [win]

  host:
    - setuptools
    - pip
    - python
    - python-build
    - numpy
    - scikit-build-core
    # upstream has it as a requirement
    - wrapt
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - setuptools
    - wrapt
    - xarray

test:
  requires:
    - netcdf4
    - xarray
  source_files:
    - test/ci_tests
  imports:
    - wrf
  commands:
    - cd test/ci_tests && python utests.py

about:
  home: https://github.com/NCAR/wrf-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Diagnostic and interpolation routines for WRF-ARW data.

extra:
  recipe-maintainers:
    - akrherz
    - erogluorhan
    - kafitzgerald
